name: CI
on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint script
        run: bash -n patch-apk.sh
      - name: Build Docker image
        run: docker build -t apk-patcher .
      - name: Create test data and patch
        run: |
          DEST=$(./create-test-data.sh)
          docker run --rm -v "$PWD/testdata:/work" apk-patcher "$(basename "$DEST")"
          docker run --rm apk-patcher --help
      - name: Upload patched APK
        uses: actions/upload-artifact@v4
        with:
          name: patched-apk
          path: testdata/*-patched.apk
